import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');

function normalizeBasePath(value) {
  const trimmed = value.replace(/^\/+|\/+$/g, '');
  return trimmed ? `/${trimmed}/` : '/';
}

const basePath = normalizeBasePath(process.env.BASE_PATH || '/');

function baseUrl(relativePath) {
  return `${basePath}${relativePath.replace(/^\/+/, '')}`;
}

function contentType(relativePath) {
  const extension = path.extname(relativePath).toLowerCase();
  return {
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.webmanifest': 'application/manifest+json; charset=utf-8',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.ico': 'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2'
  }[extension] || 'application/octet-stream';
}

function filesUnder(directory, prefix = '') {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const relativePath = path.posix.join(prefix, entry.name);
    const absolutePath = path.join(directory, entry.name);
    return entry.isDirectory() ? filesUnder(absolutePath, relativePath) : [relativePath];
  });
}

if (!fs.existsSync(path.join(dist, 'index.html'))) {
  throw new Error('Cannot generate the service worker before Vite has produced dist/index.html.');
}

const manifestPath = path.join(dist, 'manifest.webmanifest');
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.start_url = basePath;
  manifest.scope = basePath;
  manifest.icons = manifest.icons.map((icon) => ({ ...icon, src: baseUrl(icon.src) }));
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

const precacheFiles = filesUnder(dist)
  .filter((file) => file !== 'sw.js' && file !== '_headers' && file !== '_redirects' && !file.endsWith('.map'))
  .sort();
const precacheUrls = precacheFiles.map(baseUrl);
const versionHash = createHash('sha256');
for (const file of precacheFiles) {
  versionHash.update(file).update('\0').update(fs.readFileSync(path.join(dist, file))).update('\0');
}
const version = versionHash.digest('hex').slice(0, 12);

// Cache Storage is normally enough for an installed PWA, but browser cleanup
// can remove those entries while leaving the service-worker registration
// intact. Keep a copy in the worker itself so a cold offline navigation can
// still reconstruct the app shell and its local assets.
const embeddedAssets = Object.fromEntries(precacheFiles.map((file) => {
  const bytes = fs.readFileSync(path.join(dist, file));
  const type = contentType(file);
  const isText = type.startsWith('text/') || type.startsWith('application/json') || type.startsWith('application/manifest+json');
  return [baseUrl(file), isText
    ? { body: bytes.toString('utf8'), type }
    : { base64: bytes.toString('base64'), type }];
}));

const serviceWorker = `/* Generated by scripts/generate-pwa.mjs. Do not edit dist/sw.js directly. */
const CACHE_NAME = 'pickle-desk-${version}';
const CACHE_PREFIX = 'pickle-desk-';
const LEGACY_CACHE_PREFIX = 'tournament-desk-';
const APP_BASE = ${JSON.stringify(basePath)};
const INDEX_URL = APP_BASE + 'index.html';
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
const EMBEDDED_ASSETS = ${JSON.stringify(embeddedAssets)};

function embeddedResponse(url) {
  const asset = EMBEDDED_ASSETS[new URL(url, self.location.href).pathname];
  if (!asset) return undefined;
  if (asset.base64) {
    const bytes = Uint8Array.from(atob(asset.base64), (character) => character.charCodeAt(0));
    return new Response(bytes, { headers: { 'Content-Type': asset.type } });
  }
  return new Response(asset.body, { headers: { 'Content-Type': asset.type } });
}

function offlineAppShell() {
  return embeddedResponse(INDEX_URL) || new Response('Pickle Desk is unavailable offline.', {
    status: 503,
    headers: { 'Content-Type': 'text/plain; charset=utf-8' }
  });
}

function withoutRedirect(response) {
  if (!response || response.type === 'opaqueredirect') return undefined;
  if (!response.redirected) return response;
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers
  });
}

async function cacheResponse(cache, request, response) {
  const safeResponse = withoutRedirect(response);
  if (!safeResponse || !safeResponse.ok) return;
  await cache.put(request, safeResponse);
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => Promise.all(PRECACHE_URLS.map(async (url) => {
        try {
          const response = await fetch(url);
          await cacheResponse(cache, url, response);
        } catch {
          // A single unavailable asset must not block the embedded fallback.
        }
      })))
      .catch(() => undefined)
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => (key.startsWith(CACHE_PREFIX) || key.startsWith(LEGACY_CACHE_PREFIX)) && key !== CACHE_NAME)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;

  // network-first navigation keeps a deployed update fresh while preserving
  // the cached app shell for offline launches.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const safeResponse = withoutRedirect(response);
          if (!safeResponse) throw new Error('Navigation response cannot be served by the service worker.');
          void caches.open(CACHE_NAME).then((cache) => cacheResponse(cache, request, safeResponse.clone())).catch(() => undefined);
          return safeResponse;
        })
        .catch(() => caches.match(request).catch(() => undefined))
        .then((cached) => withoutRedirect(cached) || caches.match(INDEX_URL).catch(() => undefined))
        .then((cached) => withoutRedirect(cached) || offlineAppShell())
    );
    return;
  }

  event.respondWith(
    caches.match(request).catch(() => undefined)
      .then((cached) => withoutRedirect(cached) || fetch(request).then((response) => {
        const safeResponse = withoutRedirect(response);
        if (!safeResponse) throw new Error('Asset response cannot be served by the service worker.');
        void caches.open(CACHE_NAME).then((cache) => cacheResponse(cache, request, safeResponse.clone())).catch(() => undefined);
        return safeResponse;
      }))
      .catch(() => embeddedResponse(request.url) || offlineAppShell())
  );
});
`;

fs.writeFileSync(path.join(dist, 'sw.js'), serviceWorker);
console.log(`Generated PWA service worker with ${precacheUrls.length} precached files (${version}).`);
