import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');

function normalizeBasePath(value) {
  const trimmed = value.replace(/^\/+|\/+$/g, '');
  return trimmed ? `/${trimmed}/` : '/';
}

const basePath = normalizeBasePath(process.env.BASE_PATH || '/');

function baseUrl(relativePath) {
  return `${basePath}${relativePath.replace(/^\/+/, '')}`;
}

function filesUnder(directory, prefix = '') {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const relativePath = path.posix.join(prefix, entry.name);
    const absolutePath = path.join(directory, entry.name);
    return entry.isDirectory() ? filesUnder(absolutePath, relativePath) : [relativePath];
  });
}

if (!fs.existsSync(path.join(dist, 'index.html'))) {
  throw new Error('Cannot generate the service worker before Vite has produced dist/index.html.');
}

const manifestPath = path.join(dist, 'manifest.webmanifest');
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.start_url = basePath;
  manifest.scope = basePath;
  manifest.icons = manifest.icons.map((icon) => ({ ...icon, src: baseUrl(icon.src) }));
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

const precacheFiles = filesUnder(dist)
  .filter((file) => file !== 'sw.js' && !file.endsWith('.map'))
  .sort();
const precacheUrls = precacheFiles.map(baseUrl);
const version = createHash('sha256')
  .update(precacheFiles.map((file) => `${file}:${fs.statSync(path.join(dist, file)).size}`).join('\n'))
  .digest('hex')
  .slice(0, 12);

const serviceWorker = `/* Generated by scripts/generate-pwa.mjs. Do not edit dist/sw.js directly. */
const CACHE_NAME = 'pickle-desk-${version}';
const CACHE_PREFIX = 'pickle-desk-';
const LEGACY_CACHE_PREFIX = 'tournament-desk-';
const APP_BASE = ${JSON.stringify(basePath)};
const INDEX_URL = APP_BASE + 'index.html';
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => (key.startsWith(CACHE_PREFIX) || key.startsWith(LEGACY_CACHE_PREFIX)) && key !== CACHE_NAME)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;

  // network-first navigation keeps a deployed update fresh while preserving
  // the cached app shell for offline launches.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          void caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((cached) => cached || caches.match(INDEX_URL)))
    );
    return;
  }

  event.respondWith(
    caches.match(request)
      .then((cached) => cached || fetch(request).then((response) => {
        const copy = response.clone();
        void caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        return response;
      }))
  );
});
`;

fs.writeFileSync(path.join(dist, 'sw.js'), serviceWorker);
console.log(`Generated PWA service worker with ${precacheUrls.length} precached files (${version}).`);
